# Site settings
title: 致林的博客
email: haibincoder@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  致林的博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://haibincoder.github.io # the base hostname & protocol for your site
rss_url: /pages/feed.xml
author: Haibin

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'
recent_num: 20

# Social account
#weibo: haibinNetAccount
github: haibincoder

# avatar and Favicon
avatar: http://images.cnblogs.com/cnblogs_com/bincoding/909646/o_HaibinImage.png
favicon: http://images.cnblogs.com/cnblogs_com/bincoding/909646/o_HaibinImage.png

# disqus config
#disqus:
#  shortname: suyan-zh

# google analytics config
#ga:
#  id: UA-54767140-1
#  url: yansu.org

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
mathjax: disabled
sass:
  style: compressed

# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

